spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:migration
    baseline-version: 1
    url: "jdbc:mysql://localhost:3366/store"
    user: root
    password: root
    clean-disabled: false
    validate-on-migrate: true