spring:
  profiles:
    active: test
    group:
      test: common-core, flyway
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

member:
  domain:
    datasource:
      poolName: issue-domain-cp
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: "jdbc:mysql://localhost:3366/store?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul"
      username: root
      password: root
      auto-commit: false
      sqlScriptEncoding: UTF-8
      connectionTimeout: 60000
      maxLifetime: 60000
      maximumPoolSize: 5

logging:
  level:
    com.example.border: DEBUG