spring:
  profiles:
    active: local
    group:
      local: common-core
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false