spring:
  profiles:
    active: local
    group:
      local: common-core
  jpa:
    show-sql: false
    database: mysql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: false